"""empty message

Revision ID: 545428bc1129
Revises: f121f42fca52
Create Date: 2024-08-11 04:38:27.862702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545428bc1129'
down_revision = 'f121f42fca52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifics', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('specifics')

    # ### end Alembic commands ###
