"""empty message

Revision ID: f121f42fca52
Revises: 
Create Date: 2024-08-07 19:27:41.775148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f121f42fca52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_poll_id', 'poll', ['poll_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_poll_id', type_='foreignkey')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###
